FROM python:3-slim 
MAINTAINER theydonthaveit "theydonthaveit@gmail.com"

WORKDIR /app
COPY ./app /app

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE 5000
CMD ["python", "app.py"]
